#!/usr/bin/env python3
"""Convert a 32-column ASCII-art sidebar logo into a C header for A2C_DVI.

Each source row becomes one uint32_t whose bit 31 is the LEFTMOST pixel -- the
same MSB-first convention as s_screen_buffer[line][i], so the renderer can reuse
the existing two-pixels-at-a-time extraction verbatim:

    uint32_t dot = ((bits >> 29) & 0x02) | ((bits >> 31) & 0x01);
    bits <<= 2;

Usage:
    logo2header.py logo_tv.txt > sidebar_logo.h
    logo2header.py --preview logo_tv.txt
"""
import sys

WIDTH = 32


def load(path):
    rows = []
    with open(path) as fh:
        for n, raw in enumerate(fh, 1):
            line = raw.rstrip("\n")
            if not line or line.lstrip().startswith("#"):
                continue
            if len(line) != WIDTH:
                sys.exit(f"{path}:{n}: row is {len(line)} chars, expected {WIDTH}")
            bits = 0
            for col, ch in enumerate(line):
                if ch not in ".#":
                    sys.exit(f"{path}:{n}: bad char {ch!r} (use '.' or '#')")
                if ch == "#":
                    bits |= 1 << (31 - col)
            rows.append(bits)
    if not rows:
        sys.exit(f"{path}: no bitmap rows found")
    return rows


def preview(rows):
    # Two display lines per source row, so the preview matches on-screen aspect.
    for bits in rows:
        line = "".join("█" if bits & (1 << (31 - c)) else "·" for c in range(WIDTH))
        print(line)
        print(line)


def header(rows, name):
    out = []
    out.append("// Generated by logo2header.py -- do not edit by hand.")
    out.append("// bit 31 = leftmost pixel; one row per buffer scanline.")
    out.append(f"#define {name.upper()}_ROWS {len(rows)}")
    out.append(f"#define {name.upper()}_WIDTH {WIDTH}")
    out.append(f"static const uint32_t {name}[{name.upper()}_ROWS] = {{")
    for bits in rows:
        art = "".join("#" if bits & (1 << (31 - c)) else "." for c in range(WIDTH))
        out.append(f"    0x{bits:08x}, // {art}")
    out.append("};")
    return "\n".join(out)


def main():
    args = [a for a in sys.argv[1:] if a != "--preview"]
    if len(args) != 1:
        sys.exit(__doc__)
    rows = load(args[0])
    if "--preview" in sys.argv[1:]:
        preview(rows)
        print(f"\n{len(rows)} rows = {len(rows)*2} display lines, {len(rows)*4} bytes", file=sys.stderr)
    else:
        print(header(rows, "sidebar_logo_bits"))


if __name__ == "__main__":
    main()
